version: '3'

name: ethereum-fetcher

services:
  efdataabse:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - efdataabse:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - efdataabse

  efservice:
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ../:/app
    ports:
      - '3000:3000'
    depends_on:
      - efdataabse

volumes:
  efdataabse: {}
